ALTER TABLE "Trip"
ADD COLUMN "meetingPlaceId" TEXT,
ADD COLUMN "meetingLat" DOUBLE PRECISION,
ADD COLUMN "meetingLng" DOUBLE PRECISION,
ADD COLUMN "dropoffPlaceId" TEXT,
ADD COLUMN "dropoffLat" DOUBLE PRECISION,
ADD COLUMN "dropoffLng" DOUBLE PRECISION,
ADD COLUMN "routeProvider" TEXT NOT NULL DEFAULT 'static',
ADD COLUMN "routePath" JSONB,
ADD COLUMN "routeComputedAt" TIMESTAMP(3);
